# Minimal resource configuration for very constrained environments
spring:
  profiles:
    active: minimal

  # Database configuration with minimal resources
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ecomapp}
      auto-index-creation: false

  # Kafka configuration for minimal setup
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ecomapp-minimal
      auto-offset-reset: latest
      max-poll-records: 5
      fetch-min-size: 1
      session-timeout-ms: 10000
    producer:
      acks: 0
      retries: 0
      batch-size: 512
      linger-ms: 10

# Minimal server configuration
server:
  port: 8080
  tomcat:
    threads:
      max: 20
      min-spare: 2
    max-connections: 50
    accept-count: 5
  compression:
    enabled: true

# Essential actuator endpoints only
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

# Minimal logging
logging:
  level:
    com.hackathon.ecomapp: WARN
    org.springframework: ERROR
    org.mongodb: ERROR
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"
